import bcrypt from 'bcryptjs';
import mongoose from 'mongoose';
import { Template } from '../models/Template';
import { User } from '../models/User';

export const seedTemplatesData = [
  {
    _id: new mongoose.Types.ObjectId('670000000000000000000001'),
    title: 'মহান বিজয় দিবস - লাল-সবুজ শ্রদ্ধাঞ্জলি',
    occasionType: 'victory_day' as const,
    thumbnailUrl: '/templates/victory-day-bg.jpg',
    canvasDimensions: { width: 1200, height: 800 },
    layoutConfig: {
      backgroundColor: '#005A36',
      primaryColor: '#F42A41',
      secondaryColor: '#FFD700',
      leaderSlots: [
        {
          id: 'leader-1',
          label: 'শীর্ষ নেতা ১',
          x: 647,
          y: 145,
          width: 184,
          height: 184,
          shape: 'circle' as const,
          borderColor: '#FFFFFF',
        },
        {
          id: 'leader-2',
          label: 'শীর্ষ নেতা ২',
          x: 841,
          y: 145,
          width: 184,
          height: 184,
          shape: 'circle' as const,
          borderColor: '#FFFFFF',
        },
        {
          id: 'leader-3',
          label: 'শীর্ষ নেতা ৩',
          x: 1050,
          y: 145,
          width: 184,
          height: 184,
          shape: 'circle' as const,
          borderColor: '#FFFFFF',
        },
      ],
      candidateSlot: {
        x: 285,
        y: 406,
        width: 426,
        height: 426,
        blendBottom: false,
      },
      textSlots: {
        headline: {
          label: 'প্রধান স্লোগান / শিরোনাম',
          fontFamily: 'Hind Siliguri',
          fontSize: 48,
          color: '#FFFFFF',
          align: 'center' as const,
          y: 280,
          defaultBangla: 'মহান বিজয় দিবস',
          backgroundColor: '#F42A41',
        },
        candidateName: {
          label: 'প্রার্থীর নাম',
          fontFamily: 'Hind Siliguri',
          fontSize: 36,
          color: '#FFFFFF',
          align: 'center' as const,
          y: 640,
          defaultBangla: 'মোঃ রাকিবুল হাসান',
        },
        designation: {
          label: 'পদবি / পরিচয়',
          fontFamily: 'Hind Siliguri',
          fontSize: 22,
          color: '#FFD700',
          align: 'center' as const,
          y: 685,
          defaultBangla: 'সহ-সভাপতি পদপ্রার্থী',
        },
        party: {
          label: 'সংগঠন / দলীয় শাখা',
          fontFamily: 'Hind Siliguri',
          fontSize: 20,
          color: '#E2E8F0',
          align: 'center' as const,
          y: 700,
          defaultBangla: 'বাংলাদেশ জাতীয়তাবাদী দল - বিএনপি',
        },
        footerCredit: {
          label: 'প্রচারে লাইন',
          fontFamily: 'Hind Siliguri',
          fontSize: 20,
          color: '#FFFFFF',
          align: 'center' as const,
          y: 785,
          defaultBangla: 'প্রচারে: সর্বস্তরের দেশপ্রেমিক জনগণ',
          backgroundColor: '#003822',
        },
      },
    },
    isActive: true,
  },
  {
    _id: new mongoose.Types.ObjectId('670000000000000000000002'),
    title: 'নির্বাচনী প্রচারণা ও দোয়া প্রার্থী',
    occasionType: 'campaign' as const,
    thumbnailUrl: '/templates/campaign-bg.jpg',
    canvasDimensions: { width: 1200, height: 800 },
    layoutConfig: {
      backgroundColor: '#0F2027',
      primaryColor: '#203A43',
      secondaryColor: '#FFCC00',
      leaderSlots: [
        {
          id: 'leader-1',
          label: 'প্রতিষ্ঠাতা / প্রধান নেতা',
          x: 654,
          y: 145,
          width: 184,
          height: 184,
          shape: 'circle' as const,
          borderColor: '#FFFFFF',
        },
        {
          id: 'leader-2',
          label: 'দলীয় চেয়ারপারসন / সভানেত্রী',
          x: 844,
          y: 145,
          width: 184,
          height: 184,
          shape: 'circle' as const,
          borderColor: '#FFFFFF',
        },
        {
          id: 'leader-3',
          label: 'ভারপ্রাপ্ত চেয়ারম্যান / সাধারণ সম্পাদক',
          x: 1063,
          y: 145,
          width: 184,
          height: 184,
          shape: 'circle' as const,
          borderColor: '#FFFFFF',
        },
      ],
      candidateSlot: {
        x: 293,
        y: 364,
        width: 450,
        height: 450,
        blendBottom: false,
      },
      textSlots: {
        headline: {
          label: 'নির্বাচনী বার্তা',
          fontFamily: 'Hind Siliguri',
          fontSize: 48,
          color: '#FFFFFF',
          align: 'center' as const,
          y: 280,
          defaultBangla: 'জনগণের ভোটে উন্নয়নের পথে',
          backgroundColor: '#E53E3E',
        },
        candidateName: {
          label: 'প্রার্থীর নাম',
          fontFamily: 'Hind Siliguri',
          fontSize: 36,
          color: '#FFFFFF',
          align: 'center' as const,
          y: 585,
          defaultBangla: 'ব্যারিস্টার কায়সার কামাল',
        },
        designation: {
          label: 'প্রার্থিতা পদ',
          fontFamily: 'Hind Siliguri',
          fontSize: 22,
          color: '#FFD700',
          align: 'center' as const,
          y: 630,
          defaultBangla: 'ধানের শীষ মার্কায় ভোট দিন',
        },
        party: {
          label: 'দলীয় প্রতীক / মনোনয়ন',
          fontFamily: 'Hind Siliguri',
          fontSize: 20,
          color: '#A0AEC0',
          align: 'center' as const,
          y: 700,
          defaultBangla: 'আসন্ন জাতীয় সংসদ নির্বাচনে মনোনীত প্রার্থী',
        },
        footerCredit: {
          label: 'প্রচারে লাইন',
          fontFamily: 'Hind Siliguri',
          fontSize: 20,
          color: '#FFFFFF',
          align: 'center' as const,
          y: 785,
          defaultBangla: 'প্রচারে: সর্বস্তরের সচেতন ও দেশপ্রেমিক কর্মীসমাজ',
          backgroundColor: '#1A202C',
        },
      },
    },
    isActive: true,
  },
  {
    _id: new mongoose.Types.ObjectId('670000000000000000000003'),
    title: 'পবিত্র ঈদ-উল-ফিতর ও ঈদ মোবারক শুভেচ্ছা',
    occasionType: 'eid' as const,
    thumbnailUrl: '/templates/eid-bg.jpg',
    canvasDimensions: { width: 1200, height: 800 },
    layoutConfig: {
      backgroundColor: '#064E3B',
      primaryColor: '#047857',
      secondaryColor: '#F59E0B',
      leaderSlots: [
        {
          id: 'leader-1',
          label: 'শীর্ষ নেতৃত্ব ১',
          x: 635,
          y: 150,
          width: 184,
          height: 184,
          shape: 'circle' as const,
          borderColor: '#FFFFFF',
        },
        {
          id: 'leader-2',
          label: 'শীর্ষ নেতৃত্ব ২',
          x: 842,
          y: 150,
          width: 184,
          height: 184,
          shape: 'circle' as const,
          borderColor: '#FFFFFF',
        },
        {
          id: 'leader-3',
          label: 'শীর্ষ নেতৃত্ব ৩',
          x: 1060,
          y: 150,
          width: 184,
          height: 184,
          shape: 'circle' as const,
          borderColor: '#FFFFFF',
        },
      ],
      candidateSlot: {
        x: 277,
        y: 434,
        width: 426,
        height: 426,
        blendBottom: false,
      },
      textSlots: {
        headline: {
          label: 'ঈদ শুভেচ্ছা বাণী',
          fontFamily: 'Hind Siliguri',
          fontSize: 48,
          color: '#FFFFFF',
          align: 'center' as const,
          y: 280,
          defaultBangla: 'ঈদ মোবারক',
          backgroundColor: '#047857',
        },
        candidateName: {
          label: 'শুভেচ্ছান্তে নাম',
          fontFamily: 'Hind Siliguri',
          fontSize: 36,
          color: '#FFFFFF',
          align: 'center' as const,
          y: 655,
          defaultBangla: 'আলহাজ্ব মোঃ রফিকুল ইসলাম',
        },
        designation: {
          label: 'পদবি / সামাজিক পরিচয়',
          fontFamily: 'Hind Siliguri',
          fontSize: 22,
          color: '#FFD700',
          align: 'center' as const,
          y: 700,
          defaultBangla: 'পবিত্র ঈদুল ফিতরের শুভেচ্ছা ও মোবারকবাদ',
        },
        party: {
          label: 'সংগঠন / এলাকা',
          fontFamily: 'Hind Siliguri',
          fontSize: 20,
          color: '#E2E8F0',
          align: 'center' as const,
          y: 700,
          defaultBangla: 'সাধারণ সম্পাদক, ঢাকা মহানগর',
        },
        footerCredit: {
          label: 'প্রচারে লাইন',
          fontFamily: 'Hind Siliguri',
          fontSize: 20,
          color: '#FFFFFF',
          align: 'center' as const,
          y: 785,
          defaultBangla: 'শুভেচ্ছান্তে: সর্বস্তরের এলাকাবাসী',
          backgroundColor: '#064E3B',
        },
      },
    },
    isActive: true,
  },
  {
    _id: new mongoose.Types.ObjectId('670000000000000000000004'),
    title: 'শোক প্রস্তাব ও বিনম্র শ্রদ্ধাঞ্জলি',
    occasionType: 'condolence' as const,
    thumbnailUrl: '/templates/condolence-bg.jpg',
    canvasDimensions: { width: 1200, height: 800 },
    layoutConfig: {
      backgroundColor: '#171923',
      primaryColor: '#2D3748',
      secondaryColor: '#CBD5E0',
      leaderSlots: [
        {
          id: 'leader-1',
          label: 'শ্রদ্ধাভাজন ব্যক্তিত্ব ১',
          x: 630,
          y: 155,
          width: 190,
          height: 190,
          shape: 'circle' as const,
          borderColor: '#FFFFFF',
        },
        {
          id: 'leader-2',
          label: 'শ্রদ্ধাভাজন ব্যক্তিত্ব ২',
          x: 840,
          y: 155,
          width: 190,
          height: 190,
          shape: 'circle' as const,
          borderColor: '#FFFFFF',
        },
        {
          id: 'leader-3',
          label: 'শ্রদ্ধাভাজন ব্যক্তিত্ব ৩',
          x: 1055,
          y: 155,
          width: 190,
          height: 190,
          shape: 'circle' as const,
          borderColor: '#FFFFFF',
        },
      ],
      candidateSlot: {
        x: 287,
        y: 414,
        width: 428,
        height: 428,
        blendBottom: false,
      },
      textSlots: {
        headline: {
          label: 'শোক বার্তা',
          fontFamily: 'Hind Siliguri',
          fontSize: 48,
          color: '#FFFFFF',
          align: 'center' as const,
          y: 280,
          defaultBangla: 'শোক ও শ্রদ্ধাঞ্জলি',
          backgroundColor: '#2D3748',
        },
        candidateName: {
          label: 'মরহুমের নাম',
          fontFamily: 'Hind Siliguri',
          fontSize: 36,
          color: '#FFFFFF',
          align: 'center' as const,
          y: 645,
          defaultBangla: 'মরহুম আব্দুল কাদের মিয়া',
        },
        designation: {
          label: 'দোয়া / শোক প্রকাশ',
          fontFamily: 'Hind Siliguri',
          fontSize: 22,
          color: '#FFD700',
          align: 'center' as const,
          y: 690,
          defaultBangla: 'তাঁর বিদেহী আত্মার মাগফিরাত কামনা করছি',
        },
        party: {
          label: 'পরিচয়',
          fontFamily: 'Hind Siliguri',
          fontSize: 20,
          color: '#A0AEC0',
          align: 'center' as const,
          y: 700,
          defaultBangla: 'আমরা গভীর শোকাহত',
        },
        footerCredit: {
          label: 'শোক প্রকাশে',
          fontFamily: 'Hind Siliguri',
          fontSize: 20,
          color: '#FFFFFF',
          align: 'center' as const,
          y: 785,
          defaultBangla: 'শোক প্রকাশে: পরিবারবর্গ ও সর্বস্তরের শুভাকাঙ্ক্ষী',
          backgroundColor: '#171923',
        },
      },
    },
    isActive: true,
  },
];

export async function seedDatabase(force = false): Promise<void> {
  try {
    const templateCount = await Template.countDocuments();
    if (force || templateCount === 0) {
      console.log(`🌱 Seeding templates (current count: ${templateCount}, force: ${force})...`);
      for (const tplData of seedTemplatesData) {
        await Template.findByIdAndUpdate(
          tplData._id,
          tplData,
          { upsert: true, new: true, setDefaultsOnInsert: true }
        );
      }
      console.log(`🎉 Seeded ${seedTemplatesData.length} templates into database.`);
    }

    // Ensure Demo User exists
    const demoEmail = 'user@posterbabu.bd';
    const existingUser = await User.findOne({ email: demoEmail });
    if (!existingUser) {
      const salt = await bcrypt.genSalt(10);
      const passwordHash = await bcrypt.hash('poster1234', salt);
      await User.create({
        name: 'ডেমো ইউজার',
        email: demoEmail,
        passwordHash,
        role: 'user',
      });
      console.log('👤 Demo user created: user@posterbabu.bd (pass: poster1234)');
    }
  } catch (error) {
    console.error('⚠️ Seeding error:', error);
  }
}
